# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxtJ80n1B6b7NwDcCmwCiKp2kEI7L238
"""

import cv2
import pyttsx3
import requests
import time
from datetime import datetime
import os
from google import genai

# ==========================================
# 1. KONFIGURASI API & LAYANAN
# ==========================================

# Gantilah dengan API Key Anda sendiri
OPENWEATHER_API_KEY = "MASUKKAN_OPENWEATHER_API_KEY_ANDA"
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "MASUKKAN_GEMINI_API_KEY_ANDA")
KOTA = "Jakarta"  # Ganti sesuai lokasi Anda

# Inisialisasi Gemini Client
client_gemini = None
if GEMINI_API_KEY and "MASUKKAN" not in GEMINI_API_KEY:
    try:
        client_gemini = genai.Client(api_key=GEMINI_API_KEY)
    except Exception as e:
        print(f"[ERROR]: Gagal inisialisasi Gemini: {e}")

# ==========================================
# 2. INISIALISASI MESIN SUARA (TTS)
# ==========================================
engine = pyttsx3.init()
engine.setProperty('rate', 170)    # Kecepatan bicara
engine.setProperty('volume', 1.0)   # Volume suara

def jarvis_speak(text):
    """Mengeluarkan respon suara dari JARVIS."""
    print(f"\n[JARVIS]: {text}")
    try:
        engine.say(text)
        engine.runAndWait()
    except Exception as e:
        print(f"[AUDIO ERROR]: Tidak dapat mengeluarkan suara ({e})")

# ==========================================
# 3. FUNGSI LAYANAN PENDUKUNG (WEATHER & AI)
# ==========================================

def get_weather():
    """Mengambil data cuaca real-time dari OpenWeatherMap."""
    if "MASUKKAN" in OPENWEATHER_API_KEY:
        return "27 C - Cerah (Default)"
    try:
        url = f"http://api.openweathermap.org/data/2.5/weather?q={KOTA}&appid={OPENWEATHER_API_KEY}&units=metric&lang=id"
        res = requests.get(url, timeout=3).json()
        temp = res['main']['temp']
        desc = res['weather'][0]['description']
        return f"{temp:.1f} C - {desc.capitalize()}"
    except Exception:
        return "Data Cuaca Offline"

def ask_gemini(query):
    """Mengirim pertanyaan ke Gemini AI untuk mendapatkan jawaban pintar."""
    if not client_gemini:
        return "Sistem AI belum terhubung dengan API Key."
    try:
        prompt = f"Jawab ringkas dalam 1-2 kalimat pendek ala asisten JARVIS Iron Man: {query}"
        response = client_gemini.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        return response.text.strip()
    except Exception as e:
        return "Terjadi kesalahan pada modul pemrosesan AI."

# ==========================================
# 4. EFEK VISUAL HUD VISOR HELM
# ==========================================

def draw_hud(frame, faces, weather_info, status_text):
    """Menggambar grafik HUD Sci-Fi di atas layar kamera."""
    h, w, _ = frame.shape
    color_cyan = (255, 255, 0)
    color_green = (0, 255, 0)
    color_red = (0, 0, 255)

    # --- Header HUD ---
    cv2.rectangle(frame, (10, 10), (w - 10, 85), (20, 20, 20), -1)
    cv2.rectangle(frame, (10, 10), (w - 10, 85), color_cyan, 1)

    now = datetime.now().strftime("%H:%M:%S | %d-%m-%Y")
    cv2.putText(frame, "HELM VISOR JARVIS v2.5", (20, 35), cv2.FONT_HERSHEY_SIMPLEX, 0.6, color_cyan, 2)
    cv2.putText(frame, f"WAKTU : {now}", (20, 55), cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1)
    cv2.putText(frame, f"CUACA : {KOTA} ({weather_info})", (20, 75), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color_green, 1)

    # --- Status System ---
    cv2.putText(frame, f"STATUS: {status_text}", (20, h - 20), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color_cyan, 1)

    # --- Target Face Tracking ---
    for (x, y, fw, fh) in faces:
        cv2.rectangle(frame, (x, y), (x + fw, y + fh), color_cyan, 2)
        cx, cy = x + fw // 2, y + fh // 2

        # Crosshair tengah
        cv2.line(frame, (cx - 15, cy), (cx + 15, cy), color_red, 2)
        cv2.line(frame, (cx, cy - 15), (cx, cy + 15), color_red, 2)

        # Tag Informasi
        cv2.putText(frame, "TARGET DETECTED: PILOT", (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.45, color_cyan, 1)

# ==========================================
# 5. PROGRAM UTAMA
# ==========================================

def main():
    face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
    cap = cv2.VideoCapture(0)

    if not cap.isOpened():
        print("[ERROR]: Kamera helm tidak terdeteksi. Pastikan webcam terhubung.")
        return

    jarvis_speak("Sistem Helm Virtual JARVIS diaktifkan. Melakukan inisialisasi visual.")

    greeted = False
    weather_info = get_weather()
    status_text = "ONLINE [Tekan 'T' untuk Tanya AI | 'Q' untuk Keluar]"

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame = cv2.flip(frame, 1)
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        faces = face_cascade.detectMultiScale(gray, scaleFactor=1.1, minNeighbors=5, minSize=(100, 100))

        # Menyapa saat wajah pertama kali terlihat
        if len(faces) > 0 and not greeted:
            jarvis_speak("Selamat datang kembali, Sir. Semua sistem beroperasi secara optimal.")
            greeted = True

        draw_hud(frame, faces, weather_info, status_text)
        cv2.imshow("JARVIS Virtual Helmet Visor", frame)

        key = cv2.waitKey(1) & 0xFF

        # Tekan 'T' untuk memasukkan pertanyaan ke JARVIS (Input Teks / Terminal)
        if key == ord('t') or key == ord('T'):
            status_text = "MENUNGGU INPUT PERTANYAAN..."
            draw_hud(frame, faces, weather_info, status_text)
            cv2.imshow("JARVIS Virtual Helmet Visor", frame)
            cv2.waitKey(1)

            query = input("\n[INPUT PERTANYAAN UNTUK JARVIS]: ")
            if query.strip():
                status_text = f"MEMPROSES: '{query}'"
                draw_hud(frame, faces, weather_info, status_text)
                cv2.imshow("JARVIS Virtual Helmet Visor", frame)
                cv2.waitKey(1)

                response = ask_gemini(query)
                jarvis_speak(response)

            status_text = "ONLINE [Tekan 'T' untuk Tanya AI | 'Q' untuk Keluar]"

        # Tekan 'Q' untuk keluar dari program
        elif key == ord('q') or key == ord('Q'):
            jarvis_speak("Mematikan protokol helm. Sampai jumpa, Sir.")
            break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()